### ISSUE TITLE
Issues with the video

### ISSUE THREAD

**Issue by prgres** [folke/drop.nvim#1]
When I wanted to checkout the new hota*s plugin this is what appeared on Firefox. I found the issues https://bugzilla.mozilla.org/show_bug.cgi?id=1368063
which is 6 year old.

![image](https://user-images.githubusercontent.com/23465248/198706328-5d7cb483-e43f-4ca3-bae9-6e1004f1b4ed.png)

```
Media resource https://user-images.githubusercontent.com/292349/198695517-c834a9c5-8acc-4a47-9f1d-277085169754.mp4 could not be decoded. [drop.nvim](https://github.com/folke/drop.nvim)

Media resource https://user-images.githubusercontent.com/292349/198695517-c834a9c5-8acc-4a47-9f1d-277085169754.mp4 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: auto mozilla::SupportChecker::AddMediaFormatChecker(const mozilla::TrackInfo &)::(anonymous class)::operator()() const: Decoder may not have the capability to handle the requested video format with YUV444 chroma subsampling.
```

Maybe it would be better to change codec to smth else? 
(works semless on chrome btw)

**Comment by folke** [comment]
Ha, you guys are fast :)

Changed the video to something else and added a readme
