### ISSUE TITLE
feature: Transparency colorscheme support

### ISSUE THREAD

**Issue by MuteSTEVE** [folke/drop.nvim#15]
### Did you check the docs?

- [X] I have read all the drop.nvim docs

### Is your feature request related to a problem? Please describe.

Will you be able to add transparant colorscheme support in the future plan?

### Describe the solution you'd like

i use onedark colorscheme with transparency on

### Describe alternatives you've considered

nothing special, maybe something that can related to colorscheme config that will make transparancy works

### Additional context

My Alpha.nvim dashboard becoming black because it doesn't support transparency out of the box

**Comment by dtomvan** [comment]
Same goes for `catppuccin/nvim` with `transparent_background=true`. Seems to be an issue with `winblend` combined with an alpha value on the `Normal` highlight group. Probably related to the upstream neovim/neovim#18576.

**Comment by GllmR** [comment]
Hi,

![drop-transparent](https://github.com/folke/drop.nvim/assets/56537238/885f4b6b-7ddb-4392-a321-41521fc007ae)

👁️ _I can see through_ 👁️

That's Kitty & mini.starter

I'm not sure that related to Drop or Nvim, maybe it's your terminal (alacritty ?)

**Comment by dtomvan** [comment]
Hmm, how does your colorscheme define `Normal`?

**Comment by GllmR** [comment]
I use ellisonleao/gruvbox.nvim

**Comment by dtomvan** [comment]
Alright, it sets Normal and NormalFloat as guibg=NONE, maybe we could (I'll do it tomorrow if nobody did, don't have time for it now) use a minimal vimrc which just installs ministarter, drop, and sets the minimal highlights for a transparent background (on the starter).

**Comment by MuteSTEVE** [comment]
> Hi,
> 
> ![drop-transparent](https://user-images.githubusercontent.com/56537238/261683681-885f4b6b-7ddb-4392-a321-41521fc007ae.png)
> 
> 👁️ _I can see through_ 👁️
> 
> That's Kitty & mini.starter
> 
> I'm not sure that related to Drop or Nvim, maybe it's your terminal (alacritty ?)

yes i'm using alacritty as my default terminal, how does your kitty support transparency?

**Comment by dtomvan** [comment]
> I'll do it tomorrow if nobody did

I'm so sorry, haven't gotten to it yet. I'll be back after my vacation and then I'll be on it ASAP

**Comment by Uzaaft** [comment]
Just a friendly reminder @dtomvan, unless your vacation is still going on, if then, no worries!

**Comment by dtomvan** [comment]
Oh, yeah I am so sorry. Didn't take note of it properly. Thanks for the reminder!

**Comment by MrCatNerd** [comment]
the dark background and disabling transparency are happening for me too:
![image](https://github.com/folke/drop.nvim/assets/106884124/70413894-f50f-4752-90eb-53cb648e8f17)
vs:
![image](https://github.com/folke/drop.nvim/assets/106884124/5d7605d0-30bd-4bc8-bf18-a64c9454e027)

**Comment by Rizhiy** [comment]
Any updates on this? Also getting a black background with transparent background.

**Comment by Soliprem** [comment]
Also having the same issue

**Comment by BBennettChiba** [comment]
Would love to see an update. I love the idea of this plugin but it just looks terrible in my terminal
