### ISSUE TITLE
Allow the vim colorscheme to remain the same while Drop is active

### ISSUE THREAD

**Issue by nullromo** [folke/drop.nvim#16]
### Did you check the docs?

- [X] I have read all the drop.nvim docs

### Is your feature request related to a problem? Please describe.

Whenever the drops are active on the screen, the overall colorscheme of vim changes. I'd like to be able to set the colors that it changes to or have it remain the same as normal.

### Describe the solution you'd like

The default configuration should probably not affect the overall colorscheme of vim itself, just the drops. If I wanted the colorscheme to change, I would like some kind of option in the Drop config to set what it's changing to.

### Describe alternatives you've considered

An alternative solution would be to explain in the README how/why the colors are changing so I can modify the code myself.

## Vim while Drop is not active

Normal colors.

![image](https://github.com/folke/drop.nvim/assets/8991581/387a904f-f246-475d-8416-60536b552299)

## Vim while Drop is active

Why did all the colors change?

![image](https://github.com/folke/drop.nvim/assets/8991581/4635e406-50ef-4f3b-bbd1-8bfb47d04511)

**Comment by folke** [comment]
drop does not change the colorscheme.

**Comment by nullromo** [comment]
I figured out that Drop creates a floating window over the entire screen, and that's what causes all the colors to change. So yes, it's not changing the colorscheme per se, but it is messing up the colors of everything on the screen.

I see that Drop creates the highlight groups `Drop1`, `Drop1Bold`, `Drop2`, `Drop2Bold`, etc. but I think these only apply to the actual drops themselves. I can't figure out what's controlling the background color of the floating window. I can see that it's opened with `vim.api.nvim_open_win`, but nothing in that call seems to control the color.

There's also the highlight group `Drop`, which seems to get applied to the whole window via `vim.wo[M.win].winhighlight = "NormalFloat:Drop"`. This group is defined by `{ bg = "NONE", nocombine = true }`.

Do you have any idea how to make the floating window actually transparent so that it doesn't affect the colors underneath?

**Comment by nullromo** [comment]
@folke Any ideas on how to do this? I haven't gotten it to work.
