### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by quantum-booty** [folke/drop.nvim#2]
Without drop.nvim:
![image](https://user-images.githubusercontent.com/28958399/198830307-a27bf583-9a44-4589-848f-8dc3e86d8310.png)

With drop.nvim:
![image](https://user-images.githubusercontent.com/28958399/198830335-b7181b75-b787-4758-80a5-7a09edba045c.png)

**Comment by folke** [comment]
Yeah, I noticed as well. Need to look into it.

**Comment by quantum-booty** [comment]
Thanks for fixing it!

**Comment by quantum-booty** [comment]
I think this has been solved with the latest commits.
