### ISSUE TITLE
Can't open Telescope in Dashboard with drop.nvim

### ISSUE THREAD

**Issue by hatredholder** [folke/drop.nvim#3]
So, basically, whenever I try to open telescope in dashboard with this plugin running a telescope window just doesn't open, but it still does accept input and it's functionality works as excepted

Here's how it looks: 
![image](https://user-images.githubusercontent.com/86254474/198873799-d34d3d2b-a0f2-46c3-a070-60f7ace8f314.png)
Arrow points to the telescope's text input

The dashboard plugin used, if it does matter, is [dashboard.nvim](github.com/glepnir/dashboard-nvim)

**Comment by TaylorBeeston** [comment]
I have the same issue with both Telescope and [rnvimr](https://github.com/kevinhwang91/rnvimr) using [alpha.nvim](https://github.com/goolord/alpha-nvim)

**Comment by TaylorBeeston** [comment]
Btw, as a band-aid fix until @folke is back from his vacation next week, you can call `lua require("drop").hide()` prior to opening Telescope (or whatever) to fix this.

For example, I've updated my commands from this:

```lua
    dashboard.button("x", "  > Open Explorer", ":RnvimrToggle<CR>"),
    dashboard.button("f", "  > Find file", ":Telescope find_files<CR>"),
```

to this:

```lua
    dashboard.button("x", "  > Open Explorer", ":lua require('drop').hide(); vim.cmd('RnvimrToggle')<CR>"),
    dashboard.button("f", "  > Find file", ":lua require('drop').hide(); vim.cmd('Telescope find_files')<CR>"),
```
