### ISSUE TITLE
Background Question

### ISSUE THREAD

**Issue by rgnkn** [folke/drop.nvim#5]
Thanks for this "super useful" plugin! 😜

Just one simple question: Is there anyway to keep the background color of the highlight group Drop "neutral", so that the original background color of the field remains the same whether a "flake" is on it or not? (I hope you understand what I'm talking about.)

I played around with "bg", "nocombine" and "default" without any success. I even don't know if this is possible at all.

Any ideas with regards to this?

**Comment by folke** [comment]
I think I understand what you mean :)

For my colorscheme this works as expected.

Can you post a screenshot?

Make sure to set winblend=100 in your config.

**Comment by snaeil** [comment]
I am having the same issue.
I am using the material theme.

As you can see in this screenshot, the leaves' background is darker than the general background.
![2022-11-18-201506_1920x1080_scrot](https://user-images.githubusercontent.com/52743746/202784083-ed99f50d-e426-4977-a64c-9aa4fecf6cc3.png)

**Comment by rgnkn** [comment]
> I think I understand what you mean :)
> 
> For my colorscheme this works as expected.
> 
> Can you post a screenshot?
> 
> Make sure to set winblend=100 in your config.

![Screenshot from 2022-11-18 20-39-41](https://user-images.githubusercontent.com/17874137/202788700-94e36954-ff8c-425c-b18f-f055a7facc9b.png)

This uses winblend = 100 but the "problem" remains.

Further Info:
- kitty - terminal emulator
- mini.starter used to draw the "red backgrounded rectangle".

**Comment by rgnkn** [comment]
Okay, I checked and it seems to depend on the colorscheme. My favourite `material.nvim` as others show the problem as mentioned above, others are fine, some colorschemes from the very same plugin work while others don't (e.g. my "ayu" is fine, while "ayu-dark" from the same plugin shows the problem).

So, I close this issue now and need to dig into the depths of colorschemes ;-)

Please, hint me if you have any idea which setting may cause this behaviour of a colorscheme. 

Otherwise, bye 4 now.

**Comment by snaeil** [comment]
> Please, hint me if you have any idea which setting may cause this behaviour of a colorscheme.

Anything with highlight groups maybe?
