### ISSUE TITLE
Drops freeze when typing in insert mode

### ISSUE THREAD

**Issue by ConnorMooneyhan** [folke/drop.nvim#6]
This should be reproducible by the following steps:

1. Enter insert mode
2. Unfocus the system window for long enough for the drops to start falling (I don't know if it happens when you don't unfocus the window)
3. While the drops are falling, refocus the Neovim window and begin typing

The expected result of these steps is of course that the drops would go away and the editor would be back to normal, but instead the drops freeze, and the only ways I've found to get them to go away are to restart Neovim or enter normal mode then wait long enough for the drops to start falling again and then move the cursor to disable the drops.

**Comment by folke** [comment]
should be fixed now!
